import employee from "./employee.js";

const timmy = new employee('timmy',34,1232);
console.log(timmy);
timmy.addbonus(100000);
console.log(timmy.income);
const content = `
<h2 style="text-align:center;"> This was generated by JavaScript using InnerHTML. Pretty cool, right?</h2>
`;
var DOCBOI = document.querySelector(".DOCU");
 DOCBOI.innerHTML = content;
 const NA = document.createElement("article");
NA.setAttribute("id","everyday");
NA.innerHTML=`<h1>skill issue</h1>`;

 
 /**
  * 
  * Document Query selector
  * We can get stuff via Document.queryselector and document.queryselector all. 
  * document.querySelector(".experience");
  * This will find a tag with .experience class then return the html inside it. 
  * document.querySelectorAll(".gridboi");
  * This will return all tags with the gridboi class. 
  * 
  * document.querySelectorAll(".gridboi").forEach(item =>item.style.backgroundColor="red");
  * Does a foreach loop and makes all items with gridboi class and makes the background color red. 
  * Element.getElementsByClassName() older method, getting class
  * Element.getElementByID() older method getting from ID. Query selector is much better in general. 
  * 
  * document.querySelector("div").className = "kame";
  * this will change all div tags to be named "kame".
  * 
  * document.querySelector(".gridboi").attributes;
  * we can extract information from the gridboi class tag. Info regarding attributes n stuff. 
  * 
  * document.querySelector("h1").style.color="pink"; We can manipulate the CSS using this. This makes the color of h1 text to pink. 
  * 
  * document.querySelector("body").style.backgroundColor="pink";
  * changes the background of webpage to pink. 
  */
